/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface ChatMessage {
  'id' : MessageId,
  'content' : string,
  'createdAt' : Timestamp,
  'role' : MessageRole,
}
export interface ChatRequest {
  'messages' : Array<ChatTurn>,
  'conversationId' : [] | [ConversationId],
  'systemPrompt' : [] | [string],
}
export interface ChatResponse {
  'conversationId' : ConversationId,
  'message' : ChatMessage,
  'reply' : string,
}
export interface ChatStreamResponse {
  'conversationId' : ConversationId,
  'message' : ChatMessage,
  'chunks' : Array<string>,
}
export interface ChatTurn { 'content' : string, 'role' : MessageRole }
export interface Conversation {
  'id' : ConversationId,
  'title' : string,
  'messages' : Array<ChatMessage>,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
}
export type ConversationId = bigint;
export interface ConversationSummary {
  'id' : ConversationId,
  'title' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type MessageId = bigint;
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export interface UserProfile {
  'displayName' : string,
  'photoUrl' : [] | [string],
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Delete one of the caller's conversations.
   */
  'deleteConversation' : ActorMethod<[ConversationId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the public backend API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Read the caller's own profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Load one of the caller's conversations.
   */
  'getConversation' : ActorMethod<[ConversationId], [] | [Conversation]>,
  /**
   * / Read a profile by principal. A caller may only read its own profile;
   * / admins may read any profile. Anonymous callers receive null.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's conversations, newest first.
   */
  'listConversations' : ActorMethod<[], Array<ConversationSummary>>,
  /**
   * / Create or replace the caller's own profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Run a chat completion and persist the exchange for signed-in users.
   */
  'sendChatMessage' : ActorMethod<[ChatRequest], ChatResponse>,
  /**
   * / Run a chat completion and return the reply split into ordered chunks so
   * / the frontend can render it incrementally. Persists the exchange for
   * / signed-in users exactly like `sendChatMessage`; guests stay unpersisted.
   */
  'sendChatMessageStream' : ActorMethod<[ChatRequest], ChatStreamResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];