/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Nat;
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
});
export const MessageId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : MessageRole,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'messages' : IDL.Vec(ChatMessage),
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'messageCount' : IDL.Nat,
});
export const ChatTurn = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
});
export const ChatRequest = IDL.Record({
  'messages' : IDL.Vec(ChatTurn),
  'conversationId' : IDL.Opt(ConversationId),
  'systemPrompt' : IDL.Opt(IDL.Text),
});
export const ChatResponse = IDL.Record({
  'conversationId' : ConversationId,
  'message' : ChatMessage,
  'reply' : IDL.Text,
});
export const ChatStreamResponse = IDL.Record({
  'conversationId' : ConversationId,
  'message' : ChatMessage,
  'chunks' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendChatMessage' : IDL.Func([ChatRequest], [ChatResponse], []),
  'sendChatMessageStream' : IDL.Func([ChatRequest], [ChatStreamResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Nat;
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
  });
  const MessageId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : MessageRole,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'messages' : IDL.Vec(ChatMessage),
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'messageCount' : IDL.Nat,
  });
  const ChatTurn = IDL.Record({ 'content' : IDL.Text, 'role' : MessageRole });
  const ChatRequest = IDL.Record({
    'messages' : IDL.Vec(ChatTurn),
    'conversationId' : IDL.Opt(ConversationId),
    'systemPrompt' : IDL.Opt(IDL.Text),
  });
  const ChatResponse = IDL.Record({
    'conversationId' : ConversationId,
    'message' : ChatMessage,
    'reply' : IDL.Text,
  });
  const ChatStreamResponse = IDL.Record({
    'conversationId' : ConversationId,
    'message' : ChatMessage,
    'chunks' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendChatMessage' : IDL.Func([ChatRequest], [ChatResponse], []),
    'sendChatMessageStream' : IDL.Func([ChatRequest], [ChatStreamResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };